### ISSUE TITLE
Deleted questions will still count in the leaderboard

### ISSUE THREAD

**Issue by theSage21** [theSage21/orfik#3]
Questions which have been deleted will still be counted in the leaderboard. Perhaps some code is needed to fix this?

Or maybe we just have to be careful while adding them?

Altered questions don't matter. They work fine.

**Comment by Jithinqw** [comment]
Server is responding with 404 error on naming the hunt

**Comment by theSage21** [comment]
Answers are currently all lowercase. Try `orfik` as the answer?
